# Generated by Django 6.0.6 on 2026-08-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('sleep_duration', models.FloatField(default=7.0)),
                ('stress_level', models.IntegerField(default=5)),
                ('screen_time', models.CharField(default='4-6', max_length=50)),
                ('exercise_frequency', models.CharField(default='Medium', max_length=50)),
                ('reaction_time', models.FloatField(help_text='Reaction time in milliseconds')),
                ('reaction_score', models.FloatField(default=0.0, help_text='Normalized Reaction Score / 100')),
                ('visual_memory_score', models.IntegerField(default=0, help_text='Visual Pattern Score / 30')),
                ('recognition_score', models.IntegerField(default=0, help_text='Recognition Memory Score / 25')),
                ('object_location_score', models.IntegerField(default=0, help_text='Object Location Score / 25')),
                ('delayed_recall_score', models.IntegerField(default=0, help_text='Delayed Recall Score / 20')),
                ('memory_score', models.IntegerField(default=0, help_text='Combined Total Memory Score / 100')),
                ('clock_score', models.IntegerField(default=0, help_text='Clock Test Score / 20')),
                ('clock_contour_score', models.IntegerField(default=0, help_text='Contour / 4')),
                ('clock_numbers_score', models.IntegerField(default=0, help_text='Numbers / 8')),
                ('clock_hands_score', models.IntegerField(default=0, help_text='Hands / 8')),
                ('clock_image', models.CharField(blank=True, help_text='Path to drawing image', max_length=255, null=True)),
                ('cognitive_score', models.FloatField(help_text='Calculated Overall Cognitive Score / 100')),
                ('ai_predicted_score', models.FloatField(help_text='AI Predicted Cognitive Score / 100')),
                ('performance_tier', models.CharField(default='Normal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
